name: Check compatibility
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    name: Check source code compatibility
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: wasm-5.9.1-RELEASE
      - name: Run Test
        run: |
          set -eux
          make bootstrap
          cd Example/JavaScriptKitExample
          swift build --triple wasm32-unknown-wasi
          swift build --triple wasm32-unknown-wasi -Xswiftc -DJAVASCRIPTKIT_WITHOUT_WEAKREFS
